### ISSUE TITLE
BUG: there's a funny hoverbubble when you click on the circle on maps

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#705] opened 2015-08-27 04:07 UTC
Edge browser; Windows 10.

When I click on the circle on the maps, a funny little hoverbubble with no text appears.
![image](https://cloud.githubusercontent.com/assets/8903924/9512410/807e07d6-4c4f-11e5-9586-55a681efb068.png)
hrk

**Comment by LisaGee** [comment] 2015-08-30 16:21
dupe of #754

**Closed by LisaGee** 2015-08-30 16:21 UTC
