### ISSUE TITLE
BUG: Help text for "Graduation Rate" and "Salary" is "Average Actual Cost"

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#633] opened 2015-08-26 18:53 UTC
On Chrome/Android, on an institution page, touching "Graduation Rate" and "Salary 10 Years After" both give help text with content for "Average Actual Cost".  A similar problem exists further down, for "Typical Total Debt", "Typical Monthly Loan Payment", "Students Receiving Federal Aid", "Race/Ethnicity", "Test Scores", "Most Popular Programs", "Available Areas of Study".

**Comment by dnesting** [comment] 2015-08-26 18:54
![image](https://cloud.githubusercontent.com/assets/7342162/9502967/437799ee-4c02-11e5-9981-83c3b22998b2.png)

**Comment by LisaGee** [comment] 2015-08-29 01:56
Dupe of #420

**Closed by LisaGee** 2015-08-29 01:56 UTC
