### ISSUE TITLE
BUG: Available Areas of Study not obviously scrollable

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#644] opened 2015-08-26 19:04 UTC
On Chrome/Android, on the institution page, under "Available Areas of Study", the list of areas of study is in a box that is scrollable, but this isn't apparent, making it appear that the areas of study are fewer than actual.  If you touch inside the area, you can scroll around within it, but there is no indication that this is possible.  Consider putting some arrows at the top and bottom of this scrollable area when there is hidden content.

**Comment by dnesting** [comment] 2015-08-26 19:04
![image](https://cloud.githubusercontent.com/assets/7342162/9503234/b34e2c32-4c03-11e5-833f-db3437329422.png)

**Comment by ErieMeyer** [comment] 2015-08-26 19:07
@jjoteal Was there a comp for what would make this look more scrolly?

**Comment by LisaGee** [comment] 2015-08-27 12:31
Dupe of #635

**Closed by LisaGee** 2015-08-27 12:31 UTC
