### ISSUE TITLE
Bug: FIND SCHOOLS button not always present

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#681] opened 2015-08-26 22:07 UTC
Dell, Chrome, screen size one column, 6 pm. 

https://college-choice.18f.gov/

https://college-choice.18f.gov/search/?&sort=advantage:desc&page=0 

When I initially type in a name or use location, programs/degree, size on home page I have the option to click FIND SCHOOL which shows results.  Once I do an initial search, if I want to do another one, I don't see the FIND SCHOOL button.  If I want to add on to the first search, for example if I type the name then want to add location, it does it automatically so I don't need the FIND SCHOOL button.  However, if I want to clear the fields, I have to do it manually and the results still remain.  Also if I do it manually, the FIND SCHOOL button never comes back.  Even with back button I can't get it back.  The only way I got it back was to click the College Scoreboard header. Photo shows all fields empty yet results still present and FIND SCHOOL button gone. 

![no find school button](https://cloud.githubusercontent.com/assets/13317147/9507599/609d8946-4c1d-11e5-88a1-170a4498aea5.PNG)

**Comment by LisaGee** [comment] 2015-08-27 11:58
Dupe of #451

**Closed by LisaGee** 2015-08-27 11:58 UTC
