### ISSUE TITLE
As a student, I would like to be able select multiple religious affiliations so that I can find all of the schools that might be a fit for me (religion-wise).

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#879] opened 2015-08-28 22:38 UTC
h/t dmedfsa

Schools can be multiple categories (eg women-only and HBCU=Spelman, men-only and HBCU=Morehouse). Users might be looking for schools that are one of several religious affiliations. 

Should enable multi-select options.

**Comment by barkimedes** [comment] 2015-11-09 01:49
@claremccann This is a partial duplicate of #1152, so I am going to rename this issue. That bug addresses the special designation piece. This issue can remain focused on being able to select multiple religious affiliations.

It's interesting because this is two opposite behaviors. For special designations, we would expect multiple selections to result in schools that match all of the choices (conjunctive). For religious affiliation, it sounds like we would want to match schools that match any religious affiliation (disjunctive). So there will probably have to be some usability testing to see how to satisfy both of these options without confusing users.

**Closed** 2016-01-12 02:26 UTC
Labels: Area - Consumer Tool, Backlog, Bang 1 - Low, Bang For Buck 1 - Low, Buck 1 - Low, Defer, Scrub (Sabrina), Theme 3 - Students To Value Metrics, Type - Enhancement
