### ISSUE TITLE
BUG: add page selection buttons to bottom of results pages

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#700] opened 2015-08-27 03:35 UTC
Edge browser; Windows 10.

When I scroll to the bottom of the results page, there is no way to go to the next page of results without scrolling back to the top and clicking "2". Would be nice to have buttons at the bottom. Would also be nice to have a "next page" option.
https://college-choice.18f.gov/search/?&major=psychology&degree=b&size=medium&sort=advantage:desc&page=0
hrk

**Comment by LisaGee** [comment] 2015-08-27 11:47
Dupe of #484

**Closed by LisaGee** 2015-08-27 11:47 UTC
