### ISSUE TITLE
BUG: On race/ethnicity (at least on Wisconsin-Madison) 0% is showing up 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#859] opened 2015-08-28 21:56 UTC
On mac on safari on single column screen- 0% is showing up for unknown, alan and nhpi under race/ethnicity for University of Wisconsin-Madison.  

https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison

![screen shot 2015-08-28 at 5 54 20 pm](https://cloud.githubusercontent.com/assets/13317147/9557918/0018fae6-4dae-11e5-8e2a-2d5608df97ca.png)

**Comment by LisaGee** [comment] 2015-08-28 22:20
Dupe of #519

**Closed by LisaGee** 2015-08-28 22:20 UTC
