### ISSUE TITLE
Bug: Map will not scroll or zoom

### ISSUE THREAD

**Issue by samquinney2** [18F/college-choice#777] opened 2015-08-28 21:02 UTC
![image1](https://cloud.githubusercontent.com/assets/14021663/9556963/3d07ea28-4da6-11e5-9d01-128e76856466.PNG)

Browser: safari, iphone5, time: 5 PM , issue: when I clicked on a school the map will not zoom or scroll like a google map will

**Comment by LisaGee** [comment] 2015-08-28 22:57
Dupe of #231

**Closed by LisaGee** 2015-08-28 22:57 UTC
