### ISSUE TITLE
[Mobile] when editing search criteria or adding filter, clicking somewhere else should dismiss the drawe

### ISSUE THREAD

**Issue by jjtswan** [18F/college-choice#1181] opened 2015-09-07 20:06 UTC
Minor interaction glitch

Nexus 5

1. Do any search
2. Click on edit search
3. Try tapping somewhere outside

Expected result: drawer closes?
Actual result: no change.

**Comment by LisaGee** [comment] 2015-09-08 06:50
Dupe of #1072

**Closed by LisaGee** 2015-09-08 06:50 UTC
