### ISSUE TITLE
dev and staging: new data: one school not in Mid-Atlantic (region 2)

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#1062] opened 2015-09-04 23:01 UTC
Using the newest data, there is one fewer school in the Mid-Atlantic region than expected. 

Mid Atlantic contains the states: DE, DC, MD, NJ, NY, PA. When you add up the number of schools in those states, it is 602. But when searching in the Mid-Atlantic Region only 601 schools come up.

**Comment by LisaGee** [comment] 2015-09-04 23:17
@hollyallen The updated data should only affect one field CDR (moving from whole number to %).
Can you confirm that the data hasn't changed?

**Comment by LisaGee** [comment] 2015-09-04 23:18
If the data hasn't changed, but the resulting api query has, please assign the ticket to @ultrasaurus Thanks.

**Comment by hollyallen** [comment] 2015-09-04 23:37
Upon further investigation, this "bug" was also true on 8/31, so it isn't actually a new bug.

**Comment by hollyallen** [comment] 2015-09-05 01:03
I can't find a region column in the csv, so how is region being determined in the api?

**Comment by LisaGee** [comment] 2015-09-05 01:47
There is a "region" field in the data dictionary. Perhaps it's just not in the version of the .csv you're looking at?

**Comment by ultrasaurus** [comment] 2015-09-05 04:16
note: I believe that region is only present in 2013 csv

**Comment by hollyallen** [comment] 2015-09-05 14:19
Okay, I don't currently have that csv, where can I find it? Alternately I can query the API directly and find the school that way.

**Comment by ultrasaurus** [comment] 2015-09-05 19:37
@hollyallen do you have s3 access? easiest way is to pull it out of ed-college-choice-production or ed-college-choice-staging bucket (both have latest data)

**Comment by ultrasaurus** [comment] 2015-09-05 19:39
If this is a real bug, it will be either a data or API bug.  I will send a note to Clare to see if she has an idea of what this might be.

**Comment by ultrasaurus** [comment] 2015-09-05 19:48
wait, I'm confused, when I search by state I get 662 schools:  

https://ccapi-staging.18f.gov/v1/schools/?school.operating=1&2013.student.size__range=0..&school.state=DC,DE,MD,NC,NY,PA&school.degrees_awarded.predominant__range=2..3&fields=id,school.name,school.city,school.state,2013.student.size

region 2 is 601:

https://ccapi-staging.18f.gov/v1/schools/?school.operating=1&2013.student.size__range=0..&school.region_id=2&school.degrees_awarded.predominant__range=2..3&fields=id,school.name,school.city,school.state,2013.student.size

**Comment by LisaGee** [comment] 2015-09-05 20:00
@ultrasaurus your state by state query accidentally replaced NJ with NC.
In the Data, if I add up all those states, I get 602 schools.

**Comment by ultrasaurus** [comment] 2015-09-05 20:05
thanks @LisaGee -- hopefully Clare will be able to check the data.

**Comment by ultrasaurus** [comment] 2015-09-06 15:07
Info from Clare: United States Merchant Marine Academy is region 0 (US Service Schools), but the state is NY.  Apparently this is considered to be correct.

https://ccapi-staging.18f.gov/v1/schools?id=197027

![image](https://cloud.githubusercontent.com/assets/41906/9705103/2eb2b740-546e-11e5-9af9-6c480e9fd9fa.png)

**Comment by ultrasaurus** [comment] 2015-09-06 15:08
moving to "accept" for @LisaGee to confirm

**Comment by LisaGee** [comment] 2015-09-06 16:43
Not a Bug. API and Consumer Tool accurately reflect data. Closing.

**Closed by LisaGee** 2015-09-06 16:43 UTC
Labels: 6-accept, API, Consumer Tool, For Launch, p1

**Comment by hollyallen** [comment] 2015-09-07 03:20
Thank you @ultrasaurus  and @LisaGee  and Claire for tracking this down. For future reference, I do not (yet) have access to S3.
