### ISSUE TITLE
Disable some location search features when others are used

### ISSUE THREAD

**Issue by KHarshawat** [18F/college-choice#992] opened 2015-09-02 22:18 UTC
On the search page, it's confusing that there are multiple location options that look like they can be used at the same time. 

![image](https://cloud.githubusercontent.com/assets/6335546/9646142/b5abf586-519e-11e5-998c-ff56720c7c2b.png)

When a user enters a state, the other two location options should be disabled. Same with if I use a region or enter a zip code.

**Comment by LisaGee** [comment] 2015-09-04 22:26
Dupe of #329

**Closed by LisaGee** 2015-09-04 22:26 UTC
