### ISSUE TITLE
BUG: Race/Ethnicity with 0% show in the list

### ISSUE THREAD

**Issue by vgvg** [18F/college-choice#784] opened 2015-08-28 21:05 UTC
Notice the 0% nhpi and aian

<img width="242" alt="screenshot 2015-08-28 17 04 40" src="https://cloud.githubusercontent.com/assets/815256/9557052/e3bd5362-4da6-11e5-9893-ffae4472959f.png">

**Comment by LisaGee** [comment] 2015-08-28 22:20
Dupe of #519

**Closed by LisaGee** 2015-08-28 22:20 UTC
