### ISSUE TITLE
BUG: Hovertext "Graduation Rate" appearing for all three Financial Aid & Debt numbers

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#692] opened 2015-08-27 02:41 UTC
Edge browser; Windows 10.

Hovertext "Graduation Rate" is appearing for all three info circles on the right
https://college-choice.18f.gov/school/?166656-MCPHS-University

hrk

**Comment by LisaGee** [comment] 2015-08-29 03:06
Dupe of #420

**Closed by LisaGee** 2015-08-29 03:06 UTC
