### ISSUE TITLE
on iphone5 clicking the "i" for more info doesn't display more info

### ISSUE THREAD

**Issue by rongoro** [18F/college-choice#839] opened 2015-08-28 21:34 UTC
On the iphone5 going to a University's page then scrolling down to the "Average Actual Cost" section there is a blue "i" icon to get more info.  On a desktop you can hover to get more info, but on the iphone clicking it does nothing.

![img_2229](https://cloud.githubusercontent.com/assets/58707/9557548/f0b95738-4daa-11e5-9018-a9f04cd2aa64.PNG)

**Comment by LisaGee** [comment] 2015-08-29 01:39
dupe of #657

**Closed by LisaGee** 2015-08-29 01:39 UTC
