### ISSUE TITLE
BUG: "BYU" did not return any results

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#672] opened 2015-08-26 20:01 UTC
BYU is the very common abbreviation for Brigham Young University, but a search for the term yielded no results. While not the official name of the school, the abbreviation is used so universally that for the school not to show up feels like a bug.

**Comment by LisaGee** [comment] 2015-08-29 03:25
Dupe of #187

**Closed by LisaGee** 2015-08-29 03:25 UTC
