### ISSUE TITLE
BUG: Ethnicity breakdown uses ugly category names

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#665] opened 2015-08-26 19:38 UTC
iPad, Safari 
![image](https://cloud.githubusercontent.com/assets/8903924/9504077/74fa08f2-4c08-11e5-8b39-b38eb4ff13cc.jpg)

**Comment by LisaGee** [comment] 2015-08-29 03:27
Dupe of #485

**Closed by LisaGee** 2015-08-29 03:27 UTC
