### ISSUE TITLE
Bug: share feature on chrome/dell/outlook when sharing the results screen after searching for University of Wisconsin-Madison

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#660] opened 2015-08-26 19:21 UTC
When I search "University of Wisconsin-Madison and I get the results, I have the option to share.  When I share, this is what the email comes up as:

I found this on collegescorecard.ed.gov, check it out: 
https://college-choice.18f.gov/search/?name=University of Wisconsin-Madison 

On this link, it is underlined/hyperlinked from https to university and the rest is not underlined/hyperlinked. 

This was on outlook, dell, at 3:10 pm chrome on screen showing one column.

**Comment by liyanchang** [comment] 2015-08-26 21:45
![bug share results hyperlink issue](https://cloud.githubusercontent.com/assets/328073/9507151/3fd96eda-4c1a-11e5-84d8-9d1a1a01e8b9.PNG)

**Comment by liyanchang** [comment] 2015-08-26 21:46
![search button-share button issue](https://cloud.githubusercontent.com/assets/328073/9507192/6e4ba04e-4c1a-11e5-911d-fab58b658103.png)

**Comment by LisaGee** [comment] 2015-08-29 03:29
Is a dupe of #649

**Closed by LisaGee** 2015-08-29 03:29 UTC
