### ISSUE TITLE
As a Consumer, I want to see the costs of the institution broken down by income tiers under the Costs & Financial Aid section of an institution page, so that I know how much it might costs me to go there.

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#46] opened 2015-06-29 17:58 UTC
- [ ] Need list of fields / mapping
- [ ] Need design

**Comment by LisaGee** [comment] 2015-07-21 00:44
duplicate of #103

**Closed** 2015-07-21 00:45 UTC
Labels: duplicate
