### ISSUE TITLE
BUG: "Data not available" not showing on "by family income" costs area

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#915] opened 2015-08-30 22:10 UTC
![image](https://cloud.githubusercontent.com/assets/1626026/9569749/34c34284-4f42-11e5-89f0-eece66d30277.png)

I believe these $0 should instead be indicated that the data is not available.

Chrome, PC (any search method to a school w/o this data has the same issue)

https://federalist.18f.gov/preview/18F/college-choice/dev/school/?117803-Los-Angeles-County-College-of-Nursing-and-Allied-Health

**Comment by LisaGee** [comment] 2015-08-31 19:34
Dupe of #528

**Closed by LisaGee** 2015-08-31 19:34 UTC
