### ISSUE TITLE
BUG: All schools are showing 0% "Students Receiving Federal Aid"

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#693] opened 2015-08-27 02:50 UTC
Edge browser; Windows 10.

All the schools in my search are showing 0% "Students Receiving Federal Aid" in the "Financial Aid & Debt" section of school details.
![image](https://cloud.githubusercontent.com/assets/8903924/9511423/a2916e54-4c44-11e5-9510-fe59f5b5d78b.png)

https://college-choice.18f.gov/school/?217165-Bryant-University
hrk

**Comment by LisaGee** [comment] 2015-08-27 11:55
Dupe of #573

**Closed by LisaGee** 2015-08-27 11:55 UTC
