### ISSUE TITLE
Kentucky Search Issues - Multiple states showing and 4 year results in 2 year search

### ISSUE THREAD

**Issue by abisker** [18F/college-choice#1428] opened 2016-01-15 20:37 UTC
(From Michael Itzkowitz): From the home page, I am searching for 2-year colleges in Kentucky, and sometimes I have 3,052 institutions show up (from every state).  When it does work and only show Kentucky colleges (54 institutions), I have a 4-year institutions show up in my search (e.g. Allen College, Spalding). 

On: http://federalist.18f.gov/preview/18F/college-choice/staging

**Comment by yozlet** [comment] 2016-01-15 21:02
Could we get more info on this:

 1. When you search for KY-only but get 3,000 results, what's the URL in the browser's location bar?
 2. We show Spalding with the "4 year" icon but it apparently also does 2-year (associates) degrees in several different disciplines. So it's correct that Spalding shows up in the results, but possibly confusing that it says "4 year" when one is searching for 2-year. (related to #1396, maybe?)

**Comment by mitzkow** [comment] 2016-01-15 21:13
Of course, I am unable to replicate the KY now.  It appeared that it was disregarding state and searching nationally.

For the other issues (#2), within the two year search function should only pull up predominately certificate or 2-year schools.  The 4-year search should only pick up 4-year schools.


Michael Itzkowitz
Deputy Chief of Staff
Office of Postsecondary Education
(202) 453-5695

**Comment by yozlet** [comment] 2016-01-15 21:19
Thanks @mitzkow - sorry, I misunderstood the role of the predominant degree in the search.

**Comment by abisker** [comment] 2016-01-15 22:44
We had a clarifying question on this issue, basically trying to work out whether Spalding should be showing in the 2-year results. 

It has a "school.degrees_awarded.predominant" value of 3; does that mean it's actually a 4-year school, and shouldn't be showing up?

The API search includes 

&school.degrees_awarded.predominant__range=1..3&school.degrees_awarded.highest__range=2..4

so it's right that the API is returning it, but we're wondering if the query itself should be different when explicitly looking for 2-year schools?

(adding this to the issue as well as the email for clarity cc @claremccann @barkimedes @ultrasaurus)

**Comment by barkimedes** [comment] 2016-01-16 00:50
@mitzkow, @claremccann I don't know where the tradeoff should be.

Currently, the way we implemented it, if a school offers a 2 year degree (regardless of predominant degree), it will show up in the search. The school icon may say 4 year, and that can be confusing. But at least they know the school is an option. (If we keep it this way, its worth figuring out how to make this more clear)

On the other hand, what you're suggesting sounds like we should NOT show that school in the results, even if it offers an associates degree. That behavior would cause (I expect) unwanted side effects.  For example, using PREDDEG would again exclude all of the certificate schools when one searches for associates or bachelors degrees.

The way the site worked before, it was based on PREDDEG. But this seems like a more accurate/representative  aporoach

**Comment by barkimedes** [comment] 2016-01-16 00:52
When I say "worth figuring out how to make it more clear", I mean in a future version. I don't think that it is so confusing that it would harm the user experience. Thoughts @jjloteal?

**Comment by claremccann** [comment] 2016-01-16 02:23
I absolutely agree that we should show any school that offers an associate degree, regardless of whether it is predominantly 2 or 4 year. That is how we originally intended the search to work, and it is the most technically accurate. We are also considering whether there are other ways to depict degree type on the institutional pages, but let's leave that for a subsequent ticket.

**Comment by mitzkow** [comment] 2016-01-17 13:28
If all institutions that offer associate's are included in the associate's search, yes, I think this is fine for this iteration, and we can reevaluate for future versions.

Sent from my Windows Phone
________________________________

**Comment by barkimedes** [comment] 2016-01-19 03:35
@mitzkow Yes, all institutions that offer associates are included in the associates search. Similarly, all institutions that offer bachelors are included in the bachelors search. 

@yozlet @abisker Yes, Spalding should be included in the search results for 2 year degrees because it offers some associates degree(s) (even though it is a predominantly bachelors school).

Closing this issue as working as intended.

**Closed by barkimedes** 2016-01-19 03:35 UTC
Labels: Need More Info
