### ISSUE TITLE
BUG: Browser history (back button) not working correctly in search results

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#795] opened 2015-08-28 21:14 UTC
Chrome/MacOS

1. Perform a search (https://college-choice.18f.gov/search/?sort=advantage:desc)
2. Advance to the next page of results
3. Click the browser's Back button.  Observe the URL changes to the previous URL.

I expect that this will return to the previous page of results.  In actuality, the results don't change.  Hitting Reload in the browser will cause the correct results to load for that page.  This happens regardless of how deep you travel in the search results (advancing to page 10 means that clicking Back 10 times has no observable effect on the page content).

**Comment by LisaGee** [comment] 2015-08-29 04:25
dupe of #725

**Closed by LisaGee** 2015-08-29 04:25 UTC
