### ISSUE TITLE
BUG: "Mid East" as a region name is confusing to me

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#671] opened 2015-08-26 19:59 UTC
Personally I've never heard that term used referencing anything other than the area near Iraq, Israel, etc.

**Comment by ErieMeyer** [comment] 2015-08-27 01:49
Huh! I wonder if it's synonymous with midatlantic.

**Comment by LisaGee** [comment] 2015-08-29 03:26
Dupe of #709

**Closed by LisaGee** 2015-08-29 03:26 UTC
