### ISSUE TITLE
As a Consumer, as I'm perusing an Institution Detail page, I want to be able to the institution's website

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#198] opened 2015-07-21 14:05 UTC
As a Consumer, as I'm perusing an Institution Detail page, I want to be able to the institution's website (in a new window), so that I can get more detail about the school.

This data is in IPEDS.

**Comment by LisaGee** [comment] 2015-08-23 21:06
Duplicate of #492

**Closed by LisaGee** 2015-08-23 21:06 UTC
