### ISSUE TITLE
BUG: Above average green arrow only occasionally showing.

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#853] opened 2015-08-28 21:48 UTC
On University of Wisconsin-Madison, lower on the site it shows Graduation & Retention: Graduation Rate: there is a green arrow with above average.  Further up on the site it appears the same bar graph with no green arrow. 

On mac--safari--one column screen size. 

https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison
![screen shot 2015-08-28 at 5 47 55 pm](https://cloud.githubusercontent.com/assets/13317147/9557811/edec74b6-4dac-11e5-8e4e-6f51e83ea00e.png)

![screen shot 2015-08-28 at 5 47 29 pm](https://cloud.githubusercontent.com/assets/13317147/9557805/dffa3d84-4dac-11e5-8f01-351ca64b07a9.png)

**Comment by LisaGee** [comment] 2015-08-29 03:12
Dupe of #508

**Closed by LisaGee** 2015-08-29 03:12 UTC
