### ISSUE TITLE
BUG (content): need "National Average" label or key on individual school pages

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#698] opened 2015-08-27 03:19 UTC
Edge browser; Windows 10.

On the Search page, there is a key below the bar graphs indicating that the black lines are the National Average, but on the individual school pages, there is no similar key. Nothing says that the black lines are National Averages. Perhaps that's what the hovertext should say? 
![image](https://cloud.githubusercontent.com/assets/8903924/9511800/74e097ec-4c48-11e5-9d37-d9ca3bd5ed04.png)
hrk

**Comment by LisaGee** [comment] 2015-08-27 11:52
@jjoteal - I actually thought this was in progress, but I don't see a story for it.

**Comment by jjoteal** [comment] 2015-08-27 17:48
@lisa, here is the ticket where this is reported as an issue:

https://github.com/18F/college-choice/issues/466

Reassigning to @meiqimichelle

**Comment by LisaGee** [comment] 2015-08-27 19:39
Thanks,  @jjoteal! I couldn't remember the word "legend", so I was struggling to search. Closing this one as a dupe of #466

**Closed by LisaGee** 2015-08-27 19:39 UTC
Labels: 3-design, Consumer Tool, For Launch, p2
