### ISSUE TITLE
BUG: National average bar on graphs only sometimes shows percentage or $ amount 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#838] opened 2015-08-28 21:34 UTC
This is an example but I believe it happens on other schools and I know it happens on iPhone 5.  On the University of Wisconsin-Madison, several of the bar graphs show national average line but nothing next to it showing the percentage or $.  For example, average actual cost, graduation rate and salary after 10 years show the line but nothing to the right of the line.  However, further down, average actual costs shows both the line and the amount. 

https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison

![screen shot 2015-08-28 at 5 31 32 pm](https://cloud.githubusercontent.com/assets/13317147/9557556/083d470c-4dab-11e5-8db6-fe36f87c569e.png)

**Comment by LisaGee** [comment] 2015-09-04 23:26
@jjoteal Was this by design?

**Comment by jjoteal** [comment] 2015-09-04 23:32
This is the value snapshot. The national average #s don't display in the value snapshot because they should be side-by-side (Michelle has fixed this) and there isn't room to stick these numbers on the side. The #s *do* display though when the user takes a deeper dive into the parent expand/collapse section of the individual metrics. 

Additionally, this issue was marked for "post-launch" in #444

**Comment by LisaGee** [comment] 2015-09-04 23:51
Closed in favor of #444

**Closed by LisaGee** 2015-09-04 23:51 UTC
Labels: 3-design, Consumer Tool, For Launch, p3
