### ISSUE TITLE
BUG: Desktop Home: "Check Out These Schools" and "Paying for College" containers should be the same height

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#128] opened 2015-07-13 18:40 UTC
See reference comp, also with new Paying for College content. Please note that to make the columns even with the new Paying for College content, I had to add one more item to the Check Out These Schools container.

![image](https://cloud.githubusercontent.com/assets/12192706/8657671/04930db0-296d-11e5-80f9-d49ad8efe913.png)

**Comment by LisaGee** [comment] 2015-08-24 05:59
Seems like a dupe of #319

**Closed by LisaGee** 2015-08-24 05:59 UTC
Labels: bug
