### ISSUE TITLE
Location is always expanded in Edit Search

### ISSUE THREAD

**Issue by MarinaMartin** [18F/college-choice#1166] opened 2015-09-07 18:57 UTC
If I search by Programs/Degrees, the "Edit Search" on the search results page shows that section expanded. Nifty and expected behavior.

However, the Location section is always expanded. On mobile this makes this section hard to scroll through. For example if I searched by "Name" and click "Edit Search" I have to scroll through the Location section to get to "Name" again.
![screen shot 2015-09-07 at 2 57 23 pm](https://cloud.githubusercontent.com/assets/489465/9721854/ccd63d54-5570-11e5-81ff-7c3765ce8016.png)

**Comment by barkimedes** [comment] 2015-11-13 16:25
I think this issue is fixed now (and I can't reproduce it). @MarinaMartin, I'm going to close this issue, but if you are able to replicate it, please feel free to reopen.

**Closed by barkimedes** 2015-11-13 16:25 UTC
