### ISSUE TITLE
As a Consumer, I want to be able to see a list of the top performing schools in the "Check Out These Schools" section so that I can consider these schools as I figure out which schools are best suited for me

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#314] opened 2015-08-04 14:34 UTC
This page template is linked from the individual listings in the "Check Out These Schools" section on the homepage.

Mobile design comp reference:

![image](https://cloud.githubusercontent.com/assets/12192706/9063053/ce9dec38-3a93-11e5-938a-f6fc7c1c2b77.png)

Desktop design comp reference:
![image](https://cloud.githubusercontent.com/assets/12192706/9063187/4b8c2cf0-3a94-11e5-8ab5-6583e582f202.png)

@LisaGee once you approve these designs, we can push them to @meiqimichelle for development.

**Comment by meiqimichelle** [comment] 2015-08-21 07:02
@jjoteal what's the status on the content for these?

**Comment by jjoteal** [comment] 2015-08-21 12:51
@meiqimichelle per an email I received from Clare, it sounds like Ed is aiming to get these on Monday.

**Comment by LisaGee** [comment] 2015-08-26 04:19
@meiqimichelle We should discuss best way forward (or not) on this.

**Comment by meiqimichelle** [comment] 2015-08-26 04:52
@LisaGee Do we have content? I think this is one of the most interesting factoids on the site -- I hope we do!

**Comment by LisaGee** [comment] 2015-08-26 04:58
@jjoteal has them in her hands and @ErieMeyer was reviewing, so we definitely have something to put on the HP. The question for me is how to/if we can tackle the Listing page that shows them all together.

**Comment by LisaGee** [comment] 2015-08-26 05:07
@meiqimichelle Let's all discuss, b/c perhaps we can just defer this whole page. Could try instead to tweak it so link refers them to a search query instead of a listing page. Actually... Kind of like that idea and seems emminently doable. Hmmmm. 
@ErieMeyer can you take a crack at executing it this way instead? Thoughts?

**Comment by meiqimichelle** [comment] 2015-08-26 05:08
Cool. I'll tag up with @ErieMeyer and see what she thinks, and see what the content looks like.

**Comment by meiqimichelle** [comment] 2015-08-26 20:02
With content:
![screen shot 2015-08-26 at 1 00 50 pm](https://cloud.githubusercontent.com/assets/4827522/9504658/a028db90-4bf2-11e5-858d-19e97db4f972.png)

**Comment by meiqimichelle** [comment] 2015-08-26 20:05
@jjoteal This one did OK, I think -- the design still holds with the real content. Also, here's mobile:
![screen shot 2015-08-26 at 1 05 00 pm](https://cloud.githubusercontent.com/assets/4827522/9504748/1b17cb9a-4bf3-11e5-997d-078d927fe1b2.png)

**Comment by jjoteal** [comment] 2015-08-31 16:42
Assigned to @ErieMeyer for content purposes.

**Comment by ultrasaurus** [comment] 2015-08-31 18:51
if we want to select specific schools, I think a query like this would be good;  https://ccapi-staging.18f.gov/v1/schools?id=372213,104151

however, that would require a little bit of code

**Comment by LisaGee** [comment] 2015-08-31 18:54
Hmmm. For me, that results in: Internal Server Error

**Comment by ErieMeyer** [comment] 2015-09-04 21:38
The solution for this will be blog posts on Ed.gov. Will update as needed.

**Comment by LisaGee** [comment] 2015-09-07 04:57
Dupe of #916 ?

**Comment by ErieMeyer** [comment] 2015-09-08 18:21
@meiqimichelle -- I emailed these along. Will try to add them in!

**Comment by meiqimichelle** [comment] 2015-09-08 19:01
The links existing and displaying (style-wise on our site) is ready to accept so I moved this to accept. @ErieMeyer did you want to keep this open for the task of actually getting blog posts at those locations, or open a new issue?

**Comment by ErieMeyer** [comment] 2015-09-08 22:58
Lets leave this here until the links are working :)

**Comment by barkimedes** [comment] 2015-11-09 20:55
@ErieMeyer all of the links under the "Check Out These Schools" section are all live. Closing this issue (please reopen if I somehow misunderstood) :us:

**Closed by barkimedes** 2015-11-09 20:55 UTC
Labels: Area - Consumer Tool, Priority 1, Stage 6 - Accept
