### ISSUE TITLE
As a Consumer, I want to be able to share my search results via social media and email with my friends, family, and advisors so I can get their feedback and reactions.

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#202] opened 2015-07-21 14:28 UTC
As a Consumer, I want to be able to share my search results via social media and email with my friends, family, and advisors so I can get their feedback and reactions.

**Comment by diego-** [comment] 2015-07-24 20:00
duplicate of 201

**Comment by jjoteal** [comment] 2015-08-10 18:16
For the MVP, this should simply be a mailto: link

**Comment by LisaGee** [comment] 2015-08-24 05:05
as @diego- said. dupe of 201. Closing

**Closed by LisaGee** 2015-08-24 05:05 UTC
Labels: p2
