### ISSUE TITLE
Bug: no search button when searching school, must press enter key

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#636] opened 2015-08-26 18:55 UTC
On Chrome, 2:49 pm, on Dell laptop with my screen only showing one column.  Not sure if this is how you want the website to function but the only option when you want to search for a school, is to punch the "enter" key after typing a name.  There is no "search button" but there is a "share button" around in the area where a search button would/could be.  Not sure if you want a "search button" but I was looking for the "search button" initially.

**Comment by LisaGee** [comment] 2015-08-27 12:30
Dupe of #451

**Closed by LisaGee** 2015-08-27 12:30 UTC
