### ISSUE TITLE
As a developer or journalist, I want to immediately download the data so I can begin working with the data immediately. I'd also like to see a list of commonly downloaded data sets so that I can see how others are using the data. 

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#160] opened 2015-07-17 16:40 UTC
This issue is for this section of the site, _minus_ the create custom dataset ( #262) and featured downloads ( #268).

- [ ] Download data functionality
- [x] HTML/CSS MVP

Desktop reference comp:

![image](https://cloud.githubusercontent.com/assets/12192706/8752228/f4de544e-2c80-11e5-8798-889439068c84.png)

Mobile reference comp:

![image](https://cloud.githubusercontent.com/assets/12192706/8752231/f9e1f518-2c80-11e5-97cf-b7c30d726407.png)

**Comment by jjoteal** [comment] 2015-08-18 17:32
@meiqimichelle here is the final list of Featured Downloads:
- Scorecard data (all the data available on CollegeScorecard.ed.gov, one year)
- Most recent data (the most recent year of each element)
- What's new from NSLDS (all the new NSLDS completion and repayment rate data, all years)
- Post-school earnings (all the Treasury data, all years)

**Comment by LisaGee** [comment] 2015-08-18 23:15
Copy on the website should not include the text in the parens, if that wasn't obvious. 

Sent from my Windows Phone

-----Original Message-----

**Comment by meiqimichelle** [comment] 2015-08-21 04:47
This is now live on `dev`.

**Comment by LisaGee** [comment] 2015-09-05 15:07
The visual design is done, but there are no files available for download. Removing from accept.

**Comment by LisaGee** [comment] 2015-09-08 15:52
Dupe of #1015

**Closed by LisaGee** 2015-09-08 15:52 UTC
Labels: 5-in-progress, Data Tool, For Launch, Freeze, p2
