### ISSUE TITLE
BUG:Tooltip hover is cutoff on Filter options on Search Results page

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#563] opened 2015-08-25 18:32 UTC
Chrome, Win7

teps to Repro:
1. Browser is full-width of screen.
2. Go to: https://federalist.18f.gov/preview/18F/college-choice/staging/search/?state=RI&sort=completion_rate:desc
3. Hover over any of the i icons next to the filter labels and see that the text is cutoff.
![image](https://cloud.githubusercontent.com/assets/12847090/9475655/0911cec2-4b36-11e5-9b45-52d011a6ff02.png)

Expected Results:
Be able to fully read the text in the boxes.

**Comment by meiqimichelle** [comment] 2015-08-25 18:33
Closing as duplicate of #463 .

**Closed by meiqimichelle** 2015-08-25 18:33 UTC
Labels: backlog, bug, Consumer Tool, For Launch, p2
