### ISSUE TITLE
BUG: four icons would look better 2x2 instead of 3 on top row and 1 on the bottom

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#663] opened 2015-08-26 19:27 UTC
iPad, Safari 

![image](https://cloud.githubusercontent.com/assets/8903924/9503777/004aec20-4c07-11e5-9493-df63d438b3d0.jpg)

**Comment by barkimedes** [comment] 2015-11-12 06:00
@kimballce I think this one is fixed now, but it would be super awesome if you could verify it. But the reason I think it's fixed is because (as you can see in the screenshot below), the map is now below the icons, not next to them. And at the skinniest width I can make my window, they stay in one row. So I don't think what you saw is reproducible, but it'd be great to confirm it. Thanks!

<img width="398" alt="screen shot 2015-11-12 at 12 40 48 am" src="https://cloud.githubusercontent.com/assets/1174867/11111497/b94ed864-88d7-11e5-87c8-b68eb9aae8d9.png">

**Comment by saintsoup52** [comment] 2015-11-12 14:35
Does the map even need to appear on a mobile device?

**Comment by LisaGee** [comment] 2015-11-12 15:33
@barkimedes – I think you can close this. It was indeed fixed.

**Closed** 2015-11-13 18:06 UTC
Labels: Area - Consumer Tool, Stage 3 - Design
