### ISSUE TITLE
As a developer, I want to obtained detailed documentation about the API so that I know how to use it.

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#170] opened 2015-07-17 17:26 UTC
Desktop reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8753159/5f22c6fe-2c87-11e5-836b-5eae5837cb94.png)

Mobile reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8753163/63f22b20-2c87-11e5-8e15-e7159a65beb3.png)

**Comment by ultrasaurus** [comment] 2015-08-03 16:46
For the beta, would it be sufficient to give the following examples (as live links, and the resulting json response), maybe we some more narraive.

one school, one year:
http://ccapi-prod.18f.gov/school?ope_id=00143400&year=2012

same school showing just three fields for all years
http://ccapi-prod.18f.gov/school?ope_id=00143400&fields=year,admission_rate,name

list the names & sizes of all historically black schools (in 2013)
http://ccapi-prod.18f.gov/school?minority_serving.historically_black=1&fields=name,size&year=2013

you can get the value of a specific nested field like this:
http://ccapi-prod.18f.gov/school?name=American&fields=name,size,minority_serving.historically_black&year=2013

**Comment by diego-** [comment] 2015-08-03 18:07
implement the function call for ticket #183:

http://ccapi-prod.18f.gov/school?ope_id=00143400&year=2012&fields=3_yr_repayment_suppressed.income.low_income,3_yr_repayment.overall

**Comment by jjoteal** [comment] 2015-08-03 18:15
Also, please see http://cfpb.github.io/api/hmda/index.html as an example for content layout for the other pages in this section.

**Comment by diego-** [comment] 2015-08-03 18:27
converted to epic. Work tickets:

FOR BETA:
- [ ] #276: Draft Documentation (Data & API) -- In Word or a Google Doc (not on a website)
   Data dictionary + set of example queries - Shawn & Sarah (keep in GitHub?)
POST-BETA:
- [ ] Tag data dictionary with developer friendly names (P2) (Diego)
- [ ] Final Documentation (Data & API) (P1 not Beta). Every function call has name of function, list of parameters, explanation of return values and sample. Formatted how?

**Comment by LisaGee** [comment] 2015-08-24 02:01
@diego- @jjoteal - Can y'all work together to determine MVP for launch? Thanks.

**Comment by LisaGee** [comment] 2015-08-30 17:16
Marking as a dupe of #15

**Closed by LisaGee** 2015-08-30 17:16 UTC
Labels: 2-research, blocked, Data Tool, p1
