### ISSUE TITLE
BUG: Weirdie green thumb creeping into search results

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#1027] opened 2015-09-04 18:10 UTC
To recreate:

- Chrome, PC
1. Search for associates programs in history in the state of Ohio.
2. Scroll down the page of results
3. View weirdie thumb on the bottom left of page:

![image](https://cloud.githubusercontent.com/assets/1626026/9691154/c06bdf74-530e-11e5-94bf-914c35399f1c.png)

https://federalist.18f.gov/preview/18F/college-choice/staging/search/?degree=a&major=history&state=OH&sort=advantage:desc

3 column layout

**Comment by ErieMeyer** [comment] 2015-09-04 18:11
When you click on it, it slides you to the bottom of the page (really just looking at the footer)

**Comment by meiqimichelle** [comment] 2015-09-04 18:45
This should be resolved with #1008

**Comment by LisaGee** [comment] 2015-09-04 22:14
Dupe of #898

**Closed by LisaGee** 2015-09-04 22:14 UTC
