### ISSUE TITLE
BUG: National Average legend not displaying for "Value Snapshot" on individual school page

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#617] opened 2015-08-26 18:39 UTC
![image](https://cloud.githubusercontent.com/assets/12192706/9502576/2ec1111c-4c00-11e5-97fd-eedd1ba1faa3.png)

**Comment by LisaGee** [comment] 2015-08-28 23:26
Dupe of #466

**Closed by LisaGee** 2015-08-28 23:26 UTC
