### ISSUE TITLE
BUG: Key missing to show what the black line 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#849] opened 2015-08-28 21:44 UTC
https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison 

This is not just a Wisconsin problem but there is no key to show what the black line means.  Missing key.  Mac--Safari--one column screen. 

![screen shot 2015-08-28 at 5 41 05 pm](https://cloud.githubusercontent.com/assets/13317147/9557687/fc8b052e-4dab-11e5-8fd3-a4e08a429648.png)

**Comment by LisaGee** [comment] 2015-08-28 22:32
Dupe of #466

**Closed by LisaGee** 2015-08-28 22:32 UTC
