### ISSUE TITLE
BUG: in Race/Ethnicity-non resident alien and two or more have weird underscores

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#857] opened 2015-08-28 21:52 UTC
Under Wisconsin-Madison under race/ethnicity non_resident_alien and two_or_more looks weird.  

On mac-safari-one column screen. 

https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison

![screen shot 2015-08-28 at 5 52 43 pm](https://cloud.githubusercontent.com/assets/13317147/9557875/9b12366c-4dad-11e5-92f5-8f9238da3b02.png)

**Comment by LisaGee** [comment] 2015-08-29 03:13
Dupe of #485

**Closed by LisaGee** 2015-08-29 03:13 UTC
