### ISSUE TITLE
BUG: Searching for "Boston College" did not return relevant results

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#607] opened 2015-08-26 18:29 UTC
Mac Chrome (2:28pm)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9502366/cabd6d9c-4bfe-11e5-8e1d-c0a0236357c1.png)

Steps to reproduce:
1) Type in "Boston College" in search by name

**Comment by LisaGee** [comment] 2015-08-27 12:36
Dupe of #41

**Closed by LisaGee** 2015-08-27 12:36 UTC
