### ISSUE TITLE
BUG: Search results page has "Page: 1 2" at the top but not bottom

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#652] opened 2015-08-26 19:10 UTC
On Chrome/Android, the search results page has pagination at 25 results.  I can switch between pages at the top of the results, but not the bottom.  If I'm scrolling through a bunch of results, and get to the bottom, I may not remember that there were multiple pages, and the act of going back up to the top of the page to select the next page is annoying.  Either do infinite scrolling, or redundantly provide a page selection control at the bottom of the results.

**Comment by dnesting** [comment] 2015-08-26 19:11
![image](https://cloud.githubusercontent.com/assets/7342162/9503394/b05d00ba-4c04-11e5-97a8-32c0dc28d677.png)

**Comment by LisaGee** [comment] 2015-08-27 11:46
Dupe of #484

**Closed by LisaGee** 2015-08-27 11:46 UTC
