### ISSUE TITLE
BUG: graphs do not align along the bottom

### ISSUE THREAD

**Issue by m-hsiang** [18F/college-choice#638] opened 2015-08-26 18:57 UTC
Seems like they should align at the bottom to compare, currently looks like they align at the top, where there are different  numbers of words

<img width="888" alt="screen shot 2015-08-26 at 2 51 30 pm" src="https://cloud.githubusercontent.com/assets/1036641/9503055/be2f8a7a-4c02-11e5-8605-548a6150bdda.png">

**Comment by LisaGee** [comment] 2015-08-29 03:40
Dupe of #335

**Closed by LisaGee** 2015-08-29 03:40 UTC
