### ISSUE TITLE
BUG: Student ethnicity descriptions

### ISSUE THREAD

**Issue by Valer038** [18F/college-choice#757] opened 2015-08-28 20:40 UTC
https://college-choice.18f.gov/school/?239105-Marquette-University

![image](https://cloud.githubusercontent.com/assets/14021610/9556515/42de23de-4da3-11e5-86c9-2b509cadb171.png)

Time: 4:39pm
Date: 8/28/15
System: Chrome (PC)

Student ethnicity descriptions are all lower-case, several have underscores included, and several of the descriptors are accronyms.

**Comment by LisaGee** [comment] 2015-08-29 03:41
Dupe of #485 and #808

**Closed by LisaGee** 2015-08-29 03:41 UTC
