### ISSUE TITLE
Bug:  What is supposed to happen if you click on the city name on the map?

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#679] opened 2015-08-26 21:50 UTC
Dell, 5:48pm, Chrome, screen view-single column.  What is supposed to happen when clicking the city name?  I see a weird white box that has the option to exit it but not sure why it is there or why it looks like you can click the map/city name. 

https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison

![map bug](https://cloud.githubusercontent.com/assets/13317147/9507250/cf0c4b04-4c1a-11e5-9f8b-b9498e7e0d77.PNG)

**Comment by LisaGee** [comment] 2015-08-30 16:23
Dupe of #754

**Closed by LisaGee** 2015-08-30 16:23 UTC
