### ISSUE TITLE
[Mobile] $0 is shown in detailed cost by family income, when it should be n/a?

### ISSUE THREAD

**Issue by jjtswan** [18F/college-choice#1175] opened 2015-09-07 19:26 UTC
1. Find a school that does not have data for annual average cost, click to see details.

2. Expand costs which should be n/a

3. Look at the detailed average cost by family income table.

Actual: shows cost of $0 for every sample.

Expected: should say n/a?  Or just not shown.

**Comment by LisaGee** [comment] 2015-09-08 06:53
Dupe of #528

**Closed by LisaGee** 2015-09-08 06:53 UTC
