### ISSUE TITLE
Shows 1 result, but actual result not shown?

### ISSUE THREAD

**Issue by jjtswan** [18F/college-choice#1278] opened 2015-09-12 05:18 UTC
https://collegescorecard.ed.gov/search/?name=lindenwood&sort=salary:desc&page=1

![image](https://cloud.githubusercontent.com/assets/12799486/9829996/23af3ce2-58ec-11e5-8d37-8c2111daf2c7.png)

**Comment by jjtswan** [comment] 2015-09-12 05:25
Hrm, I see that no results are shown because the url param page=1 which corresponds to actual "page 2" which of course would have no results.

I'm not sure how I ended up here. I know I didn't manually tweak the URL, but I can't reproduce the series of events that got me there.  So lower priority since this seems like a weird edge case.

At the very least, it might be nice to have some logic where if the JS moved the user to a page with atual results, if they are beyond the last page.

**Comment by LisaGee** [comment] 2016-01-12 01:54
We completely redid our pagination and filtering. Cannot reproduce this anymore. Closing.

**Closed by LisaGee** 2016-01-12 01:54 UTC
Labels: Backlog, Bang 2 - Med, Bang For Buck 1 - Low, Buck 1 - Low, Priority 1, Scrub (Sabrina)
