### ISSUE TITLE
Student Body percentages that are 0% shouldn't display

### ISSUE THREAD

**Issue by rongoro** [18F/college-choice#869] opened 2015-08-28 22:14 UTC
If there are 0% of a certain Race/Ethnicity it shouldn't display at all.

https://college-choice.18f.gov/school/?194824-Rensselaer-Polytechnic-Institute

![screen shot 2015-08-28 at 6 12 35 pm](https://cloud.githubusercontent.com/assets/58707/9558182/99beb85a-4db0-11e5-952b-0b0d2b95a432.png)

**Comment by LisaGee** [comment] 2015-08-28 22:19
Dupe of #519

**Closed by LisaGee** 2015-08-28 22:19 UTC
