### ISSUE TITLE
As a developer, I'd like to know the final URL for the College Choice API

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#422] opened 2015-08-17 15:49 UTC
Addendum to #359

Of the form: https://api.data.gov/.../

**Comment by LisaGee** [comment] 2015-08-30 17:46
We know the name of the site. We should make use of it for the API.
@ErieMeyer - Can I charge you with getting this set up in conjunction with @diego- properly? Thanks.

**Comment by LisaGee** [comment] 2015-08-30 17:49
Closing as dupe of #729

**Closed by LisaGee** 2015-08-30 17:49 UTC
Labels: 2-research, API, Data Tool, For Launch, p1
