### ISSUE TITLE
BUG: Search result # for Average Actual Cost shows up as "--" on search results page but as "0" on the individual school page

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#611] opened 2015-08-26 18:34 UTC
Mac Chrome (2:32pm)

Screenshot on search results page:
![image](https://cloud.githubusercontent.com/assets/7342162/9555775/914f0c0a-4d9d-11e5-9bde-047a89a24808.png)

Screenshot on individual school page:
![image](https://cloud.githubusercontent.com/assets/12192706/9502459/69ff960a-4bff-11e5-8274-d2916f1406d0.png)

**Comment by LisaGee** [comment] 2015-08-29 02:08
Dupe of #887

**Closed by LisaGee** 2015-08-29 02:08 UTC
