### ISSUE TITLE
BUG: information icon does not click

### ISSUE THREAD

**Issue by samquinney2** [18F/college-choice#791] opened 2015-08-28 21:12 UTC
![image2](https://cloud.githubusercontent.com/assets/14021663/9557171/c763fb98-4da7-11e5-87ed-aef7513e21eb.PNG)

iphone 5, safari, 5:10 pm, issue: when I click on the information icons on the actual school page (not the search page) the bubbles won't  display any information

**Comment by LisaGee** [comment] 2015-08-29 04:27
dupe of #657

**Closed by LisaGee** 2015-08-29 04:27 UTC
