### ISSUE TITLE
[Mobile] college scorecard data page formatting needs tweaking

### ISSUE THREAD

**Issue by jjtswan** [18F/college-choice#1184] opened 2015-09-07 20:18 UTC
Lots of minor issues

1. College scorecard and data documentation links appear as white text on light gray background.  Hard to see.

2. The swipeable data insights quotations overlap the bottom  o o o o o o nav elements.

3. The download links are inconsistently aligned.

**Comment by LisaGee** [comment] 2016-01-12 01:58
Dupe of #1251

**Closed by LisaGee** 2016-01-12 01:58 UTC
Labels: Area - Data Tool, Backlog, Bang 1 - Low, Bang For Buck 1 - Low, Buck 1 - Low, Priority 3, Scrub (Sabrina), Type - Bug
