### ISSUE TITLE
HCM2 tooltip is hidden behind the graphs around it on search results page

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1186] opened 2015-09-07 21:21 UTC
e.g., university of the potomac if you search DC (using Chrome)

![image](https://cloud.githubusercontent.com/assets/13874735/9722952/d4d8dff2-5584-11e5-94ab-b4cc2fc72fc1.png)

**Comment by LisaGee** [comment] 2015-09-08 06:49
Dupe of #971

**Closed by LisaGee** 2015-09-08 06:49 UTC
