### ISSUE TITLE
bug in dev: student body 0% full time

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#1054] opened 2015-09-04 21:01 UTC
https://federalist.18f.gov/preview/18F/college-choice/dev/school/?196431-Talmudical-Seminary-Oholei-Torah (new code in dev) vs
https://college-choice.18f.gov/school/?196431-Talmudical-Seminary-Oholei-Torah (old code on prod)

0% full time (on dev)
100% full time (on prod)

**Comment by ultrasaurus** [comment] 2015-09-04 21:14
related issue:  https://github.com/18F/open-data-maker/issues/186

**Comment by ultrasaurus** [comment] 2015-09-04 21:17
FYI: definitely not an issue with the data, staging with new data matches production
![image](https://cloud.githubusercontent.com/assets/41906/9694675/b2779e66-530f-11e5-986b-f4e031206822.png)


note: full_time is derived from part time.  On dev, part-time is null

**Comment by ultrasaurus** [comment] 2015-09-04 21:21
I found the cause.  This is data.ayml on production and staging:
```
  student.part_time_share:
    source: PPTUG_EF
    type: float
    description: Share of undergraduate, degree-/certificate-seeking students who
      are part-time
  student.PPTUG_EF2:
    source: PPTUG_EF2
    type: float
    description: Share of undergraduate, degree-/certificate-seeking students who
      are part-time
```

on dev
```
  student.part_time_share:
    source: PPTUG_EF
    type: float
    description: Share of undergraduate, degree-/certificate-seeking students who
      are part-time
  student.PPTUG_EF2:
    source: PPTUG_EF2
    type: float
    description: Share of undergraduate, degree-/certificate-seeking students who
      are part-time
```

**Comment by LisaGee** [comment] 2015-09-04 21:25
These look the same to me. No?

**Comment by ultrasaurus** [comment] 2015-09-04 21:25
looks like we have two fields with same definition:  "Share of undergraduate, degree-/certificate-seeking students who are part-time"

PPTUG_EF was identified to us long ago as the field we should use for consumer tool.  Recent naming caused both fields to have same dev-friendly name, which meant last one won.  I think one should be named something else, just not sure what it should be.

**Comment by ultrasaurus** [comment] 2015-09-05 14:13
this is fixed on staging:  https://federalist.18f.gov/preview/18F/college-choice/staging/school/?196431-Talmudical-Seminary-Oholei-Torah

![image](https://cloud.githubusercontent.com/assets/41906/9699586/94530ac2-539d-11e5-8fd1-f58f831008ec.png)

**Comment by ErieMeyer** [comment] 2015-09-05 14:52
Looks great on staging!
![Uploading Screen Shot 2015-09-05 at 10.51.56 AM.png…]()

**Closed by ErieMeyer** 2015-09-05 14:52 UTC
Labels: 6-accept, backlog, Consumer Tool, For Launch, p1
