### ISSUE TITLE
BUG:I should be able to search for a subset of characters

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#358] opened 2015-08-08 17:52 UTC
Steps to Repro:
1. Navigate to: http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/college-choice/
2. Type "Berkeley" into the School Name field and hit return.
3. See 7 Results
4. Edit search to look for "Berk" and hit return.

Actual Results:
See 0 Results

Expected Results:
See 7 Results (or more....)

**Comment by LisaGee** [comment] 2015-08-24 03:38
@ultrasaurus - any idea how hard this would be to implement?

**Comment by ultrasaurus** [comment] 2015-08-24 03:58
@LisaGee based on what I've read, it is straightforward.  see my comment in:  https://github.com/18F/college-choice/issues/41  -- I think we should close this one as a dup and have the single issue https://github.com/18F/college-choice/issues/41 represent what we want to do with name search

**Comment by ultrasaurus** [comment] 2015-08-24 12:01
closing as a duplicate of https://github.com/18F/college-choice/issues/41

**Closed by ultrasaurus** 2015-08-24 12:01 UTC
Labels: API, Consumer Tool, duplicate, For Launch, p2
