### ISSUE TITLE
As an API user, I would like to be able to construct any query so that the server won't run out of memory

### ISSUE THREAD

**Issue by barkimedes** [18F/college-choice#1377] opened 2015-11-23 18:42 UTC
Story is phrased a little oddly, but the main idea is that @hollyallen reported that there are certain queries that can be constructed such that the server can run out of memory. Which is kinda bad.

@hollyallen can you provide more detail, including the impact of this issue? What kinds of queries cause this? Is it likely to happen to a lot of people (bang = high) or is this more of a theoretical issue (bang = low). Also, do you know if this is an easy/quick fix or something that would take considerable effort?

**Comment by hollyallen** [comment] 2015-11-24 18:13
More technical detail can be found in the related open-data-maker ticket: https://github.com/18F/open-data-maker/issues/63. The bang is low, but so is the buck.

https://github.com/18F/open-data-maker/issues/218 is also related in that it is a out of memory problem, but for the puma server. There is a known community solution to try, basically including a gem to do preemptive restarts. Not super elegant, but apparently effective.

The impact of both problems is that the server will go down and need to be manually restarted.

**Comment by yozlet** [comment] 2016-02-02 00:14
Have chatted with @hollyallen about this and neither of us can remember specific queries that still cause out-of-memory errors. (There used to be some, but then we added a maximum limit for results-per-page.)  The puma memory leak is not caused by specific queries (as far as we can tell) and is less pressing. I'm closing this for now.

**Closed by yozlet** 2016-02-02 00:14 UTC
Labels: Area - API, Backlog, Bang 1 - Low, Bang For Buck 1 - Low, Buck 1 - Low, Priority 1, Type - Bug
