### ISSUE TITLE
BUG: Hovertext "Graduation Rate" appearing for "Academics" section

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#697] opened 2015-08-27 03:06 UTC
Edge Browser; Windows 10.

https://college-choice.18f.gov/school/?166656-MCPHS-University
![image](https://cloud.githubusercontent.com/assets/7342162/9555479/43805d82-4d9b-11e5-8be2-883159e3e164.png)

hrk

**Comment by LisaGee** [comment] 2015-08-29 03:06
Dupe of #420

**Closed by LisaGee** 2015-08-29 03:06 UTC
