### ISSUE TITLE
Search by Degree Type should use CIP, not Preddeg

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1153] opened 2015-09-07 15:18 UTC
Currently, searching by program/degree without a program uses predominant degree awarded for the degree type. Instead, it should pull from each of the CIP variables by credential level to identify any school that offers that degree. For instance, if you select associate's degrees, it should pull any school that awarded a degree (==1 | ==2) in any of the CIPXXASSOC variables, whether or not the school is predominantly two-year.

**Comment by LisaGee** [comment] 2015-09-08 06:57
Dupe of #955

**Closed by LisaGee** 2015-09-08 06:57 UTC

**Comment by LisaGee** [comment] 2015-09-08 06:58
From Issue #1100 
Having some difficulty making the program-and-degree search work. Take CIP01 (Agriculture), and bachelor's degree. Two main problems are happening. There should be 237 schools, 243 counting schools with no threshold earnings data, but I only get 186.

The first school (with default sort threshold earnings) should be Stanford; that one doesn't show up at all, and it cuts instead to Cornell. I have no theory on this one.

It also appears predominantly two-year schools that offer a bachelor's degree in that program don't show up. For instance, Pennsylvania College of Technology and Vermont Technical College. Dropping preddeg=2 from the data file yields 147 schools, though, so still kind of inexplicable mismatch with the number of search results.
