### ISSUE TITLE
Bug:  You can not type in acronyms of schools.  Produces zero results.

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#662] opened 2015-08-26 19:25 UTC
I tried to type in "UVA" and it had zero results.  Not sure if this is something you want to have as an option.  Tried on chrome, dell, with screen size one column. 

Tried with schools like USC, UVA, UMB. 

https://college-choice.18f.gov/search/?name=UVA&sort=advantage:desc

**Comment by liyanchang** [comment] 2015-08-26 21:47
![acronyms](https://cloud.githubusercontent.com/assets/328073/9507200/7a210eae-4c1a-11e5-9e1a-3c05f429d229.PNG)

**Comment by LisaGee** [comment] 2015-08-29 03:28
Dupe of #187

**Closed by LisaGee** 2015-08-29 03:28 UTC
