### ISSUE TITLE
Trouble with program/degree search

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1100] opened 2015-09-06 15:49 UTC
Having some difficulty making the program-and-degree search work. Take CIP01 (Agriculture), and bachelor's degree. Two main problems are happening. There should be 237 schools, 243 counting schools with no threshold earnings data, but I only get 186.

The first school (with default sort threshold earnings) should be Stanford; that one doesn't show up at all, and it cuts instead to Cornell. I have no theory on this one.

It also appears predominantly two-year schools that offer a bachelor's degree in that program don't show up. For instance, Pennsylvania College of Technology and Vermont Technical College. Dropping preddeg=2 from the data file yields 147 schools, though, so still kind of inexplicable mismatch with the number of search results.

**Comment by LisaGee** [comment] 2015-09-07 03:52
@hollyallen Can you also take a look and see if you can track down the discrepancy by looking at the data?

**Comment by hollyallen** [comment] 2015-09-07 04:36
Which environment is @claremccann testing in?

**Comment by LisaGee** [comment] 2015-09-07 04:41
Production.

**Comment by hollyallen** [comment] 2015-09-07 05:28
Using the merged_current_PP_consumer.csv file I have, there are only 186 schools with PREDDEG=3, CURROPER=1, and PCIP01>0. So that matches. 

In my data, PCIP01 = 0 for Stanford.

I do not know how the tool knows that a predominantly two-year school offers a bachelor's degree.

I also don't know what "threshold earnings data" is.

**Comment by claremccann** [comment] 2015-09-07 12:23
Need to look at CIP01BACH, etc to see specific program offerings by degree type. Threshold earnings is gt_25k_p6.

**Comment by hollyallen** [comment] 2015-09-07 17:22
Based on my findings, I am guessing that the consumer tool is using PREDDEG and not CIP01BACH, though I don't have a csv with CIP01BACH in it.

**Comment by claremccann** [comment] 2015-09-07 21:53
If you have the Featured Download -- all data elements file, the CIP data are in there.

**Comment by LisaGee** [comment] 2015-09-08 06:59
Dupe of #955

**Closed by LisaGee** 2015-09-08 06:59 UTC
Labels: backlog, Consumer Tool, For Launch, Freeze, p1
