### ISSUE TITLE
As a consumer, I would like to compare the key metrics of my top schools side by side so that I can easily see which school is the better fit for me

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1352] opened 2015-09-28 19:38 UTC

**Comment by LisaGee** [comment] 2015-10-26 18:24
@jjoteal Can you formulate this as a Story? Trying to make sure we're accounting for context or background of why this may be a request at the moment. Did you hear a request for this from students?

**Comment by jjoteal** [comment] 2015-11-02 18:52
Done. Yes, this specific request came up during our in-person usability test sessions with high school students in October. They would like the ability to "save" schools and then compare them side-by-side -- especially the key metrics.

**Comment by LisaGee** [comment] 2015-12-07 03:44
Duplicate of #285?

**Closed by LisaGee** 2015-12-07 03:44 UTC
Labels: Area - Consumer Tool, Backlog, Bang 2 - Med, Bang For Buck 1 - Low, Buck 3 - High, Priority 2, Scrub (Sabrina), Theme 3 - Students To Value Metrics, Type - Enhancement
