### ISSUE TITLE
BUG: Financial Aid & Debt / Students Paying Down Their Debt / National Average

### ISSUE THREAD

**Issue by schakj** [18F/college-choice#799] opened 2015-08-28 21:16 UTC
Does not appear.

**Comment by LisaGee** [comment] 2015-08-29 05:05
@schakj Can you be more specific? What's the URL? And please also provide a screenshot. Thanks.

**Comment by barkimedes** [comment] 2015-11-01 23:19
@schakj There isn't enough information here to understand what the bug even is. You're welcome to reopen this with more details (steps to reproduce, screenshots, an explanation, etc.). But for now I'm closing this because I just don't know what else we can possibly do with it.

**Closed by barkimedes** 2015-11-01 23:19 UTC
Labels: Need More Info
