### ISSUE TITLE
Allow separate data import without major API server downtime

### ISSUE THREAD

**Issue by yozlet** [18F/college-choice#530] opened 2015-08-24 16:58 UTC
At present, data import is part of the API server process, and requires one such process to run for several hours before API service can resume. This is bad for many reasons.

@ozzyjohnson managed to do ES import/export of data files, so one solution here is to have a separate server process (not running on the main ccapi CF route) run the import, and then when it's ready, shut down the main API up for a minute while the ES data is swapped in.

**Comment by ultrasaurus** [comment] 2015-08-26 18:26
@yozlet I think the issue is that we delete the index pretty agressively when we import new data, so it's not really about app availability, but instead the fact the during indexing es doesn't actually have any data.  In theory I beleive we now have the right code that would allow us to reindex a new dataset without deleting the index, as long as we're not changing how types or fields are mapped, but I haven't actually tested that theory or looked at that code recently.

**Comment by ultrasaurus** [comment] 2015-08-26 18:32
closing as a dup of https://github.com/18F/college-choice/issues/394

**Closed by ultrasaurus** 2015-08-26 18:32 UTC
Labels: 2-research, For Beta, Infrastructure, p1
