### ISSUE TITLE
BUG: iPhone display weirdness for data tool

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#1070] opened 2015-09-05 04:15 UTC
This is on an iPhone in safari
![image](https://cloud.githubusercontent.com/assets/1626026/9697661/94e45e76-5363-11e5-8f46-a0620676fe66.jpg)
![image](https://cloud.githubusercontent.com/assets/1626026/9697662/94f77394-5363-11e5-91a5-293772356f2d.jpg)
![image](https://cloud.githubusercontent.com/assets/1626026/9697663/94f802dc-5363-11e5-8058-8f9c7b2ef524.jpg)

**Comment by meiqimichelle** [comment] 2015-09-05 05:19
The data part of the site does not have much responsive code. Desktop users were prioritized for that part of the site so unfortunately this display is as expected for those pages. /cc @LisaGee

**Comment by LisaGee** [comment] 2016-01-12 02:14
Dupe of #1251

**Closed by LisaGee** 2016-01-12 02:14 UTC
Labels: Area - Data Tool, Backlog, Bang 1 - Low, Bang For Buck 1 - Low, Buck 2 - Med, Priority 2, Scrub (Sabrina), Theme 2 - Influencers To Value Metrics, Type - Enhancement
