### ISSUE TITLE
Enhancement: iPad - Available areas of Study not clear that it is scrollable

### ISSUE THREAD

**Issue by vgvg** [18F/college-choice#787] opened 2015-08-28 21:10 UTC
This is more of a usability thing rather than a "bug", but the text area that shows available areas of study is not immediately clear that it is scrollable on an iPad. At first it lead me to believe that it ended at Education. A lot of people might not know to scroll to see more. Small UI design tweak would fix it.

<img width="645" alt="screenshot 2015-08-28 17 07 16" src="https://cloud.githubusercontent.com/assets/815256/9557161/aa52f748-4da7-11e5-873f-a521ca20c298.png">

**Comment by LisaGee** [comment] 2015-08-29 04:31
Dupe of #635

**Closed by LisaGee** 2015-08-29 04:31 UTC
