### ISSUE TITLE
BUG: Can't find colleges from acronyms

### ISSUE THREAD

**Issue by liyanchang** [18F/college-choice#615] opened 2015-08-26 18:38 UTC
![screen shot 2015-08-26 at 2 38 08 pm](https://cloud.githubusercontent.com/assets/328073/9502530/ecebc6d8-4bff-11e5-87e4-6bf522db6efa.png)

![screen shot 2015-08-26 at 2 38 44 pm](https://cloud.githubusercontent.com/assets/328073/9502536/f500ddd6-4bff-11e5-9d26-6b664292f23e.png)

![screen shot 2015-08-26 at 2 38 57 pm](https://cloud.githubusercontent.com/assets/328073/9502539/fce05414-4bff-11e5-86b5-d1cc2da87d42.png)

Firefox 39.0
1024x768
OSX 10.8.5

**Comment by LisaGee** [comment] 2015-08-29 02:09
Dupe of #187

**Closed by LisaGee** 2015-08-29 02:09 UTC
