### ISSUE TITLE
BUG: Key missing to show what the black line 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#847] opened 2015-08-28 21:41 UTC
https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison 

This is not just a Wisconsin problem but there is no key to show what the black line means.  Missing key.  Mac--Safari--one column screen. 

![screen shot 2015-08-28 at 5 42 27 pm](https://cloud.githubusercontent.com/assets/13317147/9557705/2ceb7438-4dac-11e5-9889-d37b92178fb9.png)

**Comment by LisaGee** [comment] 2015-08-28 22:38
Dupe of #466

**Closed by LisaGee** 2015-08-28 22:38 UTC
