### ISSUE TITLE
Bug: Data showing as 0% in label instead of N/A

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#878] opened 2015-08-28 22:34 UTC
Yeshiva College of the Nations Capital shows as 0% grad rate when searching men's only schools, but bar graph shows as Data Not Available.

**Comment by LisaGee** [comment] 2015-08-29 02:42
C150_4_POOLED_SUPP==PrivacySuppressed for this school.
Not Available should be displaying in Label as well as Graph.

**Comment by LisaGee** [comment] 2015-08-31 19:36
Dupe of #903

**Closed by LisaGee** 2015-08-31 19:36 UTC
Labels: B, Consumer Tool, For Launch, p2
