### ISSUE TITLE
Indiana search issues - 4 year results in a 2 year search

### ISSUE THREAD

**Issue by abisker** [18F/college-choice#1429] opened 2016-01-15 20:39 UTC
(From Michael Itzkowitz): I get a bunch of 4-year institutions when doing 2-year search in Indiana. 

On: http://federalist.18f.gov/preview/18F/college-choice/staging

**Comment by yozlet** [comment] 2016-01-15 21:16
Closing as duplicate of #1428

**Closed by yozlet** 2016-01-15 21:16 UTC
